package GroupBuy;

import Adt.ListInterface;
import Entity.GroupBuyMemberEntity;
import Entity.GroupBuyEntity;
import Main.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ng Theng Yang
 */

public class groupBuyModifyGui extends javax.swing.JFrame {

    private ListInterface<GroupBuyEntity> currentGroupBuys;
    private GroupBuyEntity currentGroupBuy;
    private GroupBuyMemberEntity[] groupBuyMembers;
    private int editPosition;
    
    public groupBuyModifyGui(int editPosition) {
        initComponents();
        setLocationRelativeTo(null);
        initValues(editPosition);
        initFieldValues();
        setTableValue();
    }
    
    private void initValues(int editPosition){
        currentGroupBuys = mainMenu.currentGroupBuys;
        currentGroupBuy = new GroupBuyEntity();
        this.editPosition = editPosition;
    }
    
    private void initFieldValues(){
        currentGroupBuy = currentGroupBuys.getEntry(editPosition);
        
        GroupBuyId.setText(currentGroupBuy.getGroupBuyId());
        ItemGroupId.setText(currentGroupBuy.getItemGroupId());
        Desc.setText(currentGroupBuy.getGroupBuyDescription());
        MaxMember.setValue(currentGroupBuy.getGroupBuyMaxMember());
        OriPrice.setText(String.valueOf(currentGroupBuy.getGroupBuyOriginalPrice()));
        Discount.setText(String.valueOf(currentGroupBuy.getGroupBuyDiscountRate()));
        DiscPrice.setText(String.valueOf(currentGroupBuy.getGroupBuyFinalPrice()));
    }
    
    private void setTableValue(){
        groupBuyMembers = currentGroupBuy.getMemberEntity();
        int totalMemberOfGroupBuy = currentGroupBuy.getTotalNumberOfGroupBuyMembers();
        DefaultTableModel model = (DefaultTableModel) EditTable.getModel();
        for(int row = 0; row < 5; row++){
            Object[] jTableData = new Object[5];
            jTableData[0] = "-";
            jTableData[1] = "-";
            jTableData[2] = "-";
            jTableData[3] = "-";
            jTableData[4] = "-";
            if(row < totalMemberOfGroupBuy){
                jTableData[0] = groupBuyMembers[row].getMemberId();
                jTableData[1] = groupBuyMembers[row].getName();
                jTableData[2] = groupBuyMembers[row].getGender();
                jTableData[3] = groupBuyMembers[row].getIcNo();
                jTableData[4] = groupBuyMembers[row].getPhoneNo();
            }
            for(int columnIndex = 0; columnIndex < 5; columnIndex++)
                model.setValueAt(jTableData[columnIndex], row, columnIndex);
        }
    }
    
    private void modifyMember(int buttonPosition){
        int totalMemberEntry = currentGroupBuy.getTotalNumberOfGroupBuyMembers();
        if(totalMemberEntry > 0 && buttonPosition <= totalMemberEntry){ 
            setVisible(false);
            new groupBuyJoinMemberGui(editPosition, buttonPosition).setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(this, "Unable to modify ! Please select the row that has value to perform modify!");
    }
    
    private void removeMember(int buttonPosition){
        int totalMemberEntry = currentGroupBuy.getTotalNumberOfGroupBuyMembers();
        if(totalMemberEntry > 0 && buttonPosition <= totalMemberEntry){ 
            currentGroupBuy.removeGroupBuyMember(buttonPosition);
            currentGroupBuys.replace(currentGroupBuy, editPosition);
            setTableValue();
        }
        else
            JOptionPane.showMessageDialog(this, "Unable to remove ! Please select the row that has value to perform edit!");
    }
    
    private void exitForm(){
        setVisible(false);
        new GroupBuy.groupBuy().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Remove1 = new javax.swing.JButton();
        Change1 = new javax.swing.JButton();
        Change2 = new javax.swing.JButton();
        Remove2 = new javax.swing.JButton();
        Remove3 = new javax.swing.JButton();
        Change3 = new javax.swing.JButton();
        Change4 = new javax.swing.JButton();
        Remove4 = new javax.swing.JButton();
        Remove5 = new javax.swing.JButton();
        Change5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        EditTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        retrieveSmallPanel = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        GroupBuyId = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        Desc = new javax.swing.JTextPane();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        MaxMember = new javax.swing.JSpinner();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        OriPrice = new javax.swing.JTextField();
        Discount = new javax.swing.JTextField();
        DiscPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        ItemGroupId = new javax.swing.JTextField();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Group Buy Maintenance");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        Remove1.setBackground(new java.awt.Color(255, 255, 255));
        Remove1.setText("Remove");
        Remove1.setActionCommand("view1");
        Remove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove1ActionPerformed(evt);
            }
        });

        Change1.setBackground(new java.awt.Color(255, 255, 255));
        Change1.setText("Change");
        Change1.setActionCommand("view1");
        Change1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Change1ActionPerformed(evt);
            }
        });

        Change2.setBackground(new java.awt.Color(255, 255, 255));
        Change2.setText("Change");
        Change2.setActionCommand("view2");
        Change2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Change2ActionPerformed(evt);
            }
        });

        Remove2.setBackground(new java.awt.Color(255, 255, 255));
        Remove2.setText("Remove");
        Remove2.setActionCommand("view2");
        Remove2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove2ActionPerformed(evt);
            }
        });

        Remove3.setBackground(new java.awt.Color(255, 255, 255));
        Remove3.setText("Remove");
        Remove3.setActionCommand("view3");
        Remove3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove3ActionPerformed(evt);
            }
        });

        Change3.setBackground(new java.awt.Color(255, 255, 255));
        Change3.setText("Change");
        Change3.setActionCommand("view3");
        Change3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Change3ActionPerformed(evt);
            }
        });

        Change4.setBackground(new java.awt.Color(255, 255, 255));
        Change4.setText("Change");
        Change4.setActionCommand("view4");
        Change4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Change4ActionPerformed(evt);
            }
        });

        Remove4.setBackground(new java.awt.Color(255, 255, 255));
        Remove4.setText("Remove");
        Remove4.setActionCommand("view4");
        Remove4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove4ActionPerformed(evt);
            }
        });

        Remove5.setBackground(new java.awt.Color(255, 255, 255));
        Remove5.setText("Remove");
        Remove5.setActionCommand("view5");
        Remove5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Remove5ActionPerformed(evt);
            }
        });

        Change5.setBackground(new java.awt.Color(255, 255, 255));
        Change5.setText("Change");
        Change5.setActionCommand("view5");
        Change5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Change5ActionPerformed(evt);
            }
        });

        EditTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MemberId", "Name", "Gender", "IC No.", "Phone No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        EditTable.setRowHeight(30);
        jScrollPane1.setViewportView(EditTable);

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel2.setText("Member List");

        retrieveSmallPanel.setBackground(new java.awt.Color(255, 255, 255));
        retrieveSmallPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modify Group Buy Member Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft JhengHei", 1, 18))); // NOI18N

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel31.setText("Group Buy Code: ");

        GroupBuyId.setEditable(false);

        Desc.setEditable(false);
        jScrollPane5.setViewportView(Desc);

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel32.setText("Group Description: ");

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel33.setText("Group Maximum Member: ");

        MaxMember.setModel(new javax.swing.SpinnerNumberModel(2, 2, 5, 1));
        MaxMember.setEnabled(false);

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel34.setText("Item Original Price / Unit: ");

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel35.setText("Item Discount Rate: ");

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel36.setText("Item Discounted Price / Unit: ");

        jLabel37.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel37.setText("RM ");

        jLabel38.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel38.setText("RM ");

        OriPrice.setEditable(false);

        Discount.setEditable(false);

        DiscPrice.setEditable(false);

        jLabel1.setText("%");

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel39.setText("Item Group Id: ");

        ItemGroupId.setEditable(false);

        javax.swing.GroupLayout retrieveSmallPanelLayout = new javax.swing.GroupLayout(retrieveSmallPanel);
        retrieveSmallPanel.setLayout(retrieveSmallPanelLayout);
        retrieveSmallPanelLayout.setHorizontalGroup(
            retrieveSmallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(retrieveSmallPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(retrieveSmallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(retrieveSmallPanelLayout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MaxMember, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(retrieveSmallPanelLayout.createSequentialGroup()
                        .addGroup(retrieveSmallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(retrieveSmallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GroupBuyId, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(retrieveSmallPanelLayout.createSequentialGroup()
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Discount, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(retrieveSmallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, retrieveSmallPanelLayout.createSequentialGroup()
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel37)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(DiscPrice))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, retrieveSmallPanelLayout.createSequentialGroup()
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel38)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(OriPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(retrieveSmallPanelLayout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItemGroupId, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        retrieveSmallPanelLayout.setVerticalGroup(
            retrieveSmallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(retrieveSmallPanelLayout.createSequentialGroup()
                .addGroup(retrieveSmallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GroupBuyId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(retrieveSmallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ItemGroupId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(retrieveSmallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(retrieveSmallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaxMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(retrieveSmallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel38)
                    .addComponent(OriPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(retrieveSmallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(Discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addGroup(retrieveSmallPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37)
                    .addComponent(DiscPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 19, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Change3)
                            .addComponent(Change4)
                            .addComponent(Change1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Change2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Change5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Remove4)
                                .addComponent(Remove1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Remove5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(Remove2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Remove3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(retrieveSmallPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Change1)
                    .addComponent(Remove1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Change2)
                    .addComponent(Remove2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Change3)
                    .addComponent(Remove3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Change4)
                    .addComponent(Remove4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Change5)
                    .addComponent(Remove5))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(retrieveSmallPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        exitForm();
    }//GEN-LAST:event_BackActionPerformed

    private void Change1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Change1ActionPerformed
        // TODO add your handling code here:
        modifyMember(1);
    }//GEN-LAST:event_Change1ActionPerformed

    private void Change2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Change2ActionPerformed
        // TODO add your handling code here:
        modifyMember(2);
    }//GEN-LAST:event_Change2ActionPerformed

    private void Change3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Change3ActionPerformed
        // TODO add your handling code here:
        modifyMember(3);
    }//GEN-LAST:event_Change3ActionPerformed

    private void Change4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Change4ActionPerformed
        // TODO add your handling code here:
        modifyMember(4);
    }//GEN-LAST:event_Change4ActionPerformed

    private void Change5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Change5ActionPerformed
        // TODO add your handling code here:
        modifyMember(5);
    }//GEN-LAST:event_Change5ActionPerformed

    private void Remove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove1ActionPerformed
        // TODO add your handling code here:
        removeMember(1);
    }//GEN-LAST:event_Remove1ActionPerformed

    private void Remove2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove2ActionPerformed
        // TODO add your handling code here:
        removeMember(2);
    }//GEN-LAST:event_Remove2ActionPerformed

    private void Remove3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove3ActionPerformed
        // TODO add your handling code here:
        removeMember(3);
    }//GEN-LAST:event_Remove3ActionPerformed

    private void Remove4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove4ActionPerformed
        // TODO add your handling code here:
        removeMember(4);
    }//GEN-LAST:event_Remove4ActionPerformed

    private void Remove5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Remove5ActionPerformed
        // TODO add your handling code here:
        removeMember(5);
    }//GEN-LAST:event_Remove5ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        exitForm();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(groupBuyModifyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(groupBuyModifyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(groupBuyModifyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(groupBuyModifyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new groupBuyModifyGui().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Change1;
    private javax.swing.JButton Change2;
    private javax.swing.JButton Change3;
    private javax.swing.JButton Change4;
    private javax.swing.JButton Change5;
    private javax.swing.JTextPane Desc;
    private javax.swing.JTextField DiscPrice;
    private javax.swing.JTextField Discount;
    private javax.swing.JTable EditTable;
    private javax.swing.JTextField GroupBuyId;
    private javax.swing.JTextField ItemGroupId;
    private javax.swing.JSpinner MaxMember;
    private javax.swing.JTextField OriPrice;
    private javax.swing.JButton Remove1;
    private javax.swing.JButton Remove2;
    private javax.swing.JButton Remove3;
    private javax.swing.JButton Remove4;
    private javax.swing.JButton Remove5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel retrieveSmallPanel;
    // End of variables declaration//GEN-END:variables
}
