package Main;

import Entity.MemberHistoriesGroupBuy;
import Adt.CircularArrayQueue;
import Adt.QueueInterface;
import Entity.Member;
import Adt.StackInterface;
import Entity.ItemGroup;
import Adt.ArrayStack;
import Adt.ListInterface;
import Entity.GroupBuyEntity;
import Adt.ArrayList;
import ItemGroup.*;
import Member.*;

import GroupBuy.*;

/**
 *
 * @author Khoo Shi Zhao, Ng Theng Yang, Yeap Ying Thung
 */

public class mainMenu extends javax.swing.JFrame {
    public static QueueInterface<Member> members = new CircularArrayQueue<Member>();
    public static StackInterface<ItemGroup> itemGroups = new ArrayStack<ItemGroup>();
    public static ListInterface<GroupBuyEntity> currentGroupBuys = new ArrayList<GroupBuyEntity>();
    public static ListInterface<GroupBuyEntity> historyGroupBuys = new ArrayList<GroupBuyEntity>();
    private Member member = new Member();
    private ItemGroup itemGroup = new ItemGroup();
    private MemberHistoriesGroupBuy historyData = new MemberHistoriesGroupBuy();
    private GroupBuyEntity groupBuy = new GroupBuyEntity();
    private static boolean getDatabase = false;
    /**
     * Creates new form NewJFrame
     */
    public mainMenu() {
        initComponents();
        setLocationRelativeTo(null);
        getDataCollection();
    }
    
    private void getDataCollection(){
        if(!getDatabase){
            //item group1
            itemGroup = new ItemGroup("I001","Cookies",2,10.00,4,9.60);
            itemGroup.addItemGroupTotalTransaction();
            itemGroups.push(itemGroup);
            //item group2
            itemGroup = new ItemGroup("I002","Keyboard", 2, 200.00, 4,192.00);
            itemGroup.addItemGroupTotalTransaction();
            itemGroups.push(itemGroup);
            
            //member 1
            member = new Member("M001","Khoo Shi Zhao","010328070547","0109325371","Male");
            groupBuy = new GroupBuyEntity("G001", "I001", "Cookies", 2, 10.00, 4, 9.60);
            historyData = new MemberHistoriesGroupBuy(groupBuy);
            historyGroupBuys.add(groupBuy, 1);
            member.enqueueHistoriesGroupBuy(historyData);
            groupBuy = new GroupBuyEntity("G002", "I002", "Keyboard", 2, 200.00, 4, 192.00);
            historyData = new MemberHistoriesGroupBuy(groupBuy);
            historyGroupBuys.add(groupBuy, 1);
            member.enqueueHistoriesGroupBuy(historyData);
            members.enqueue(member);
            //member 2
            member = new Member("M002","Ng Theng Yang","011111070313","0109324376","Male");
            members.enqueue(member);
            getDatabase = true;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonMemberManagement = new javax.swing.JButton();
        jButtonItemGroupManagement = new javax.swing.JButton();
        jButtonGroupBuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Why So Cheap Group Buy System");

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel1.setText("Why So Cheap Group Buy System");

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 36)); // NOI18N
        jLabel2.setText("Main Menu");

        jButtonMemberManagement.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonMemberManagement.setText("Member Management");
        jButtonMemberManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMemberManagementActionPerformed(evt);
            }
        });

        jButtonItemGroupManagement.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonItemGroupManagement.setText("Item Group Management");
        jButtonItemGroupManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonItemGroupManagementActionPerformed(evt);
            }
        });

        jButtonGroupBuy.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButtonGroupBuy.setText("Group Buy");
        jButtonGroupBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGroupBuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButtonItemGroupManagement)
                        .addGap(51, 51, 51)
                        .addComponent(jButtonMemberManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jButtonGroupBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(287, 287, 287)
                    .addComponent(jLabel2)
                    .addContainerGap(271, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonItemGroupManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMemberManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jButtonGroupBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 64, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(71, 71, 71)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(344, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMemberManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMemberManagementActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new MemberMaintenance().setVisible(true);
    }//GEN-LAST:event_jButtonMemberManagementActionPerformed

    private void jButtonItemGroupManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonItemGroupManagementActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new ItemGroupMaintenance().setVisible(true);
    }//GEN-LAST:event_jButtonItemGroupManagementActionPerformed

    private void jButtonGroupBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGroupBuyActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new groupBuy().setVisible(true);
    }//GEN-LAST:event_jButtonGroupBuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGroupBuy;
    private javax.swing.JButton jButtonItemGroupManagement;
    private javax.swing.JButton jButtonMemberManagement;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
